
CREATE TABLE MOVIES(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCR VARCHAR(1000),
    VIDEO VARCHAR(255),
    IMAGE VARCHAR(255),
    CATEGORY VARCHAR(255)
);


CREATE TABLE USERS(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD1 VARCHAR(255)
   
);


CREATE TABLE SUBTITLES (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    SBTL_FILE VARCHAR(255),
    MOVIE_ID INT(11),
    LANG_CODE VARCHAR(11),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID)
);